import RootLayout from "@/layout-custom/RootLayout";
import "./globals.css";
import Provider from "@/redux/ReduxProvider";

export const metadata = {
  title: "Darkak IT",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <html lang="en">
      <body className="bg-deep-1  w-[100vw] h-[100vh]">
        <Provider>
          <RootLayout content={children} />
        </Provider>
      </body>
    </html>
  );
}
